Repository pravocodes/Hacktoberfest2024, pull requests merged in 2024-10, with the labels that each got.

#5 Implement Binary Search Functionality
  .vscode/settings.json
  cpp/.cph/.c++ algorithms.cpp_d5d7ec2e6847003f61b365350767f2e0.prob
  cpp/c++ algorithms.cpp
Labels: hacktoberfest-accepted

#4 update README.md
  README.md
Labels: hacktoberfest-accepted

#7 Create sort.js
  javascript/sort.js
Labels: hacktoberfest-accepted

#6 Added solution for Create Container_with_Most_Water.cpp
  cpp/Container_with_Most_Water.cpp
Labels: Hacktoberfest2024, hacktoberfest-accepted

#9 Added a Simple Web Project
  WebProjects/drumsticks/images/crash.png
  WebProjects/drumsticks/images/drumstick.jpg
  WebProjects/drumsticks/images/kick.png
  WebProjects/drumsticks/images/music.jpg
  WebProjects/drumsticks/images/snare.png
  WebProjects/drumsticks/images/tom1.png
  WebProjects/drumsticks/images/tom2.png
  WebProjects/drumsticks/images/tom3.png
  WebProjects/drumsticks/images/tom4.png
  WebProjects/drumsticks/index.html
  WebProjects/drumsticks/main.js
  WebProjects/drumsticks/sounds/crash.mp3
  WebProjects/drumsticks/sounds/kick-bass.mp3
  WebProjects/drumsticks/sounds/snare.mp3
  WebProjects/drumsticks/sounds/tom-1.mp3
  WebProjects/drumsticks/sounds/tom-2.mp3
  WebProjects/drumsticks/sounds/tom-3.mp3
  WebProjects/drumsticks/sounds/tom-4.mp3
  WebProjects/drumsticks/styles.css
Labels: good first issue, Hacktoberfest2024, hacktoberfest-accepted

#10 Code in c++ algorithms.cpp has been solve completely with no errors a…
  cpp/c++ algorithms.cpp
Labels: good first issue, Hacktoberfest2024, hacktoberfest-accepted

#12 Addition of new codes in cpp
  cpp/BST1.cpp
  cpp/BT.cpp
  cpp/InsertionSort.cpp
  cpp/MatchingParenthesis.cpp
  cpp/MergeLists.cpp
  cpp/QueueImplementation.cpp
  cpp/QueueList.cpp
  cpp/Reverse-Alternate-K-Nodes.cpp
  cpp/StackImplementation.cpp
  cpp/StackUsingQueue.cpp
Labels: good first issue, Hacktoberfest2024, hacktoberfest-accepted

#16 fix:#15 : fix footer spacing
  WebProjects/drumsticks/index.html
  WebProjects/drumsticks/styles.css
Labels: good first issue, Hacktoberfest2024, hacktoberfest-accepted

#19 added gsap animation codes
  WebAnimations/.DS_Store
  WebAnimations/.gitignore
  WebAnimations/README.md
  WebAnimations/index.html
  WebAnimations/package-lock.json
  WebAnimations/package.json
  WebAnimations/postcss.config.js
  WebAnimations/public/vite.svg
  WebAnimations/src/App.jsx
  WebAnimations/src/BasicAnimation.jsx
  WebAnimations/src/FadeAnimtion.jsx
  WebAnimations/src/MoreAnimation.jsx
  WebAnimations/src/ScrollAnim2.jsx
  WebAnimations/src/ScrollAnimation.jsx
  WebAnimations/src/SvgAnimation.jsx
  WebAnimations/src/TextAnimation.jsx
  WebAnimations/src/TimeLine.jsx
  WebAnimations/src/assets/react.svg
  WebAnimations/src/index.css
  WebAnimations/src/main.jsx
  WebAnimations/tailwind.config.js
  WebAnimations/vite.config.js
  WebAnimations/yarn.lock
Labels: good first issue, Hacktoberfest2024, hacktoberfest-accepted

#14 Stuff related to Array concepts.
  C++/QuestionsOfArrays/2Darray.cpp
  C++/QuestionsOfArrays/bubbleSort.cpp
  C++/QuestionsOfArrays/charSort.cpp
  C++/QuestionsOfArrays/countSort.cpp
  C++/QuestionsOfArrays/diagonalSum.cpp
  C++/QuestionsOfArrays/insertion.cpp
  C++/QuestionsOfArrays/selectionSort.cpp
  C++/QuestionsOfArrays/spiralMatrix.cpp
  C++/QuestionsOfArrays/trappingRainwater.cpp
  cpp/dijkestra.cpp
Labels: good first issue, Hacktoberfest2024, hacktoberfest-accepted

#24 pattern_upload_c
  cpp/pattern/Inverted-Left-Half-Pyramid-Pattern.c
  cpp/pattern/Inverted-Right-Half-Pyramid-Pattern.c
  cpp/pattern/Inverted-full-pyrm.c
  cpp/pattern/Rhombus-pattern.c
  cpp/pattern/diamond.c
  cpp/pattern/full-pyrm.c
  cpp/pattern/left-hal-pyrm.c
  cpp/pattern/right-hal-pyrm.c
  cpp/pattern/second-largest.c
  cpp/pattern/tempCodeRunnerFile.c
Labels: good first issue, Hacktoberfest2024, hacktoberfest-accepted

#25 Implementation stack using array , dynamic array & Linked list
  C++/STACK/STACK_USING_ARRAY.cpp
  C++/STACK/STACK_using_DYN_array.cpp
  C++/STACK/STACK_using_Linked_list.cpp
Labels: good first issue, Hacktoberfest2024, hacktoberfest-accepted

#26 Optimized Approach
  C++/QuestionsOfArrays/trappingRainwater.cpp
Labels: good first issue, Hacktoberfest2024, hacktoberfest-accepted

#27 mergesort in cpp
  C++/QuestionsOfArrays/mergesort.cpp
Labels: good first issue, Hacktoberfest2024, hacktoberfest-accepted

#22 Added a basic React Code for a Food App feel free to develop Further
  WebProjects/Food App/src/app.jsx
  WebProjects/Food App/src/components/ui/button.js
  WebProjects/Food App/src/components/ui/card.js
  WebProjects/Food App/src/pay.jsx
Labels: good first issue, Hacktoberfest2024, hacktoberfest-accepted

#30 boolean matrix
  C++/QuestionsOfArrays/Boolean_matrix.cpp
Labels: good first issue, Hacktoberfest2024, hacktoberfest-accepted

#31 Added optimized Solution for NUMBERS BOX pattern
  cpp/pattern/NumberPattern.cpp
  cpp/pattern/NumberPattern.exe
Labels: good first issue, Hacktoberfest2024, hacktoberfest-accepted

#32 bug/isfull()
  C++/STACK/STACK_USING_ARRAY.cpp
Labels: good first issue, Hacktoberfest2024, hacktoberfest-accepted

#36 Create MaximumNumberOfPointsThatLieOnTheSameStraightLine
  C++/QuestionsOfArrays/ProgramThatReturnsMaximumNumberOfPointsThatLieOnTheSameStraightLine.cpp
Labels: good first issue, Hacktoberfest2024, hacktoberfest-accepted

#37 Create Bubblesort.cpp
  cpp/Bubblesort.cpp
Labels: good first issue, Hacktoberfest2024, hacktoberfest-accepted

#33 Drum kit css and js code change
  WebProjects/drumsticks/index.html
  WebProjects/drumsticks/main.js
  WebProjects/drumsticks/styles.css
Labels: good first issue, Hacktoberfest2024, hacktoberfest-accepted

#43 Create stackusinglinkedlist222.c
  C++/STACK/stackusinglinkedlist222.c
Labels: good first issue, Hacktoberfest2024, hacktoberfest-accepted

#42 car-price-prediction
  python/Car_price_prediction.ipynb
Labels: good first issue, Hacktoberfest2024, hacktoberfest-accepted

#57 Create SortArray.cpp
  C++/QuestionsOfArrays/SortArray.cpp
Labels: good first issue, Hacktoberfest2024, hacktoberfest-accepted

#46 Kruskal's Algorithm
  cpp/Kruskal.cpp
Labels: Hacktoberfest2024, hacktoberfest-accepted

#47 Update State Using Array in JS
  javascript/State_Using_Array.js
Labels: Hacktoberfest2024, hacktoberfest-accepted

#65 Create Second_largest_array.cpp
  C++/QuestionsOfArrays/Second_largest_array.cpp
Labels: Hacktoberfest2024, hacktoberfest-accepted

#48 new update
  C++/BinaryTree.cpp
Labels: good first issue, Hacktoberfest2024, hacktoberfest-accepted

#53 Create BallGame.js
  javascript/BallGame.js
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#55 Create Binary Search in C++
  c++/Binary Search  in C++
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#56 Here’s an implementation of Merge Sort in C++
  Merge_Sort.cpp
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#58 Create StackOfArray.cpp
  C++/STACK/StackOfArray.cpp
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#61 Adding stack code
  C++/STACK/stack.cpp
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#63 Adding a File of Check Balanced PArenthesis Using Stack , Two Stack Implementations using Stack , Reverse of String using stack
  C++/STACK/Check_Balance_Bracket.cpp
  C++/STACK/Reverse_String.cpp
  C++/STACK/TWO_Stack_IN_Array.cpp
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#67 added rank transform of an array
  C++/QuestionsOfArrays/rankTransformOfArray.cpp
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#69 UPDATED THE README.md file
  README.md
  image.jpg
Labels: enhancement, Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#71 Insertion Sort Algorithm
  C++/QuestionsOfArrays/InsertionSort.cpp
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#72 Python project
  python/Air_Quality_prediction/Air_Quality.csv
  python/Air_Quality_prediction/Air_Quality_Prediction.py
  python/Air_Quality_prediction/output.png
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#74 added
  python/bubsort.py
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#77 Add a React Project
  ReactProject/YoutubeClone/.gitignore
  ReactProject/YoutubeClone/package-lock.json
  ReactProject/YoutubeClone/package.json
  ReactProject/YoutubeClone/public/favicon.ico
  ReactProject/YoutubeClone/public/index.html
  ReactProject/YoutubeClone/src/App.js
  ReactProject/YoutubeClone/src/components/ChannelCard.jsx
  ReactProject/YoutubeClone/src/components/ChannelDetail.jsx
  ReactProject/YoutubeClone/src/components/Feed.jsx
  ReactProject/YoutubeClone/src/components/Loader.jsx
  ReactProject/YoutubeClone/src/components/Navbar.jsx
  ReactProject/YoutubeClone/src/components/SearchBar.jsx
  ReactProject/YoutubeClone/src/components/SearchFeed.jsx
  ReactProject/YoutubeClone/src/components/Sidebar.jsx
  ReactProject/YoutubeClone/src/components/VideoCard.jsx
  ReactProject/YoutubeClone/src/components/VideoDetail.jsx
  ReactProject/YoutubeClone/src/components/Videos.jsx
  ReactProject/YoutubeClone/src/components/index.js
  ReactProject/YoutubeClone/src/index.css
  ReactProject/YoutubeClone/src/index.js
  ReactProject/YoutubeClone/src/utils/constants.js
  ReactProject/YoutubeClone/src/utils/fetchFromAPI.js
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#80 Simple todo app
  javascript/todo-app/index.html
  javascript/todo-app/script.js
  javascript/todo-app/style.css
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#81 Create merge.js
  javascript/merge.js
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#127 Create Hollow Diamond Pattern in C++
  cpp/pattern/HollowDiamond.cpp
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#126 Update kadane_algorithm.cpp
  cpp/kadane_algorithm.cpp
Labels: good first issue, Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#125 Create study.py
  python/study.py
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#123 Create depth_first_search.cpp
  C++/depth_first_search.cpp
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#122 Create bubble_sort.cpp
  C++/bubble_sort.cpp
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#121 Create binary_search.cpp
  C++/binary_search.cpp
Labels: good first issue, Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#120 Create fibonacci_memoization.cpp
  C++/fibonacci_memoization.cpp
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#116 added webproject for hactoberfest
  WebProjects/Personal_Finance_Manger/Webpage 5/index.html
  WebProjects/Personal_Finance_Manger/Webpage 5/script.js
  WebProjects/Personal_Finance_Manger/Webpage 5/styles.css
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#107 Add Web Calculator
  WebProjects/Web Calculator/icon/calculator-icon.png
  WebProjects/Web Calculator/index.html
  WebProjects/Web Calculator/script.js
  WebProjects/Web Calculator/style.css
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#103 Create DijkstraAlgorithm.cpp
  C++/DijkstraAlgorithm.cpp
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#105 add: adds secondLargest program in python
  python/secondLargest.py
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#104 Added heap sort in python
  python/heapsort.py
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#108 Apple vision clone added
  Apple clone/Apple vision image.png
  Apple clone/images/Vision00001.png
  Apple clone/images/Vision00002.png
  Apple clone/images/Vision00003.png
  Apple clone/images/Vision00004.png
  Apple clone/images/Vision00005.png
  Apple clone/images/Vision00006.png
  Apple clone/images/Vision00007.png
  Apple clone/images/Vision00008.png
  Apple clone/images/Vision00009.png
  Apple clone/images/Vision00010.png
  Apple clone/images/Vision00011.png
  Apple clone/images/Vision00012.png
  Apple clone/images/Vision00013.png
  Apple clone/images/Vision00014.png
  Apple clone/images/Vision00015.png
  Apple clone/images/Vision00016.png
  Apple clone/images/Vision00017.png
  Apple clone/images/Vision00018.png
  Apple clone/images/Vision00019.png
  Apple clone/images/Vision00020.png
  Apple clone/images/Vision00021.png
  Apple clone/images/Vision00022.png
  Apple clone/images/Vision00023.png
  Apple clone/images/Vision00024.png
  Apple clone/images/Vision00025.png
  Apple clone/index.html
  Apple clone/script.js
  Apple clone/style.css
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#101 merged two sorted linked lists.
  cpp/merge_sort.cpp
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#99 Create to_do_list.html
  to_do_list.html
Labels: good first issue, Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#98 4Sum.cpp
  C++/4Sum.cpp
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#102 Snake Game Using the JS
  javascript/snake_game/index.html
  javascript/snake_game/script.js
  javascript/snake_game/styles.css
  pattern/Inverted-Left-Half-Pyramid-Pattern.c
  pattern/Inverted-Right-Half-Pyramid-Pattern.c
  pattern/Inverted-full-pyrm.c
  pattern/Rhombus-pattern.c
  pattern/diamond.c
  pattern/full-pyrm.c
  pattern/left-hal-pyrm.c
  pattern/right-hal-pyrm.c
  pattern/second-largest.c
  pattern/tempCodeRunnerFile.c
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#94 Add Merge Sort Algorithm in CPP
  cpp/Merge_sort.cpp
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#96 Implemented Counting Sort in Python
  CountingSort.py
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#109 Create Preorder Traversal on Binary Tree.cpp
  c++/Preorder Traversal on Binary Tree.cpp
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#113 add bfs graph traversal algorithm implemented in cpp
  C++/QUEUE/bfs_traversal.cpp
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#111 Added Segment Tree in C++
  cpp/segmentTree.cpp
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#88 Drag and Drop site
  webdevproject/contributing.md
  webdevproject/drag_drop_site/img1.jpg
  webdevproject/drag_drop_site/img2.jpg
  webdevproject/drag_drop_site/img3.jpg
  webdevproject/drag_drop_site/index.html
  webdevproject/drag_drop_site/script.js
  webdevproject/drag_drop_site/style.css
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#85 [Program Addition] : selection sort program
  C++/Selection_Sort.cpp
  C++/Selection_Sort.exe
  python/Quick_sort.py
Labels: good first issue, Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted

#92 Implement merge sort in C #91
  C++/MergeSort.c
Labels: Hacktoberfest, Hacktoberfest2024, hacktoberfest-accepted
